### ISSUE TITLE
Reasons of android:allowBackup = 'false'

### ISSUE THREAD

**Issue by ybbarng** [joshjdevl/libsodium-jni#101]
Hello.
Thanks to your effort to make it easy to use libsodium.

I'd like to ask you the reason of why [android:allowBackup is set to false](https://github.com/joshjdevl/libsodium-jni/blob/master/src/main/AndroidManifest.xml#L2).
Because of it, I have to use this library with using 'tools.replace....' to make set it to default ('true').
However, it is better that removing that makes no need for 'tools.replace...' or something similar.

Thanks

**Comment by joshjdevl** [comment]
Please refer to #76
