### ISSUE TITLE
Adding crypto_aead_xchacha20poly1305_ietf*

### ISSUE THREAD

**Issue by jeprojects** [joshjdevl/libsodium-jni#116]
I would like to do a pull request to add these methods.

Looking at your tests, I can't see any prior aead tests. Where would you like me to add tests?

**Comment by jeprojects** [comment]
Already added those methods and tests.

https://github.com/joshjdevl/libsodium-jni/pull/115

**Comment by joshjdevl** [comment]
Merged #115
