### ISSUE TITLE
No Key Derivation Functions

### ISSUE THREAD

**Issue by rmtmckenzie** [joshjdevl/libsodium-jni#121]
I need key derivation functions for a project. No need for a fancy api, just access to the native calls is all I need.

I've submitted pr #120, hopefully that does enough. I can't get the full build to work on my computer right now but it did get past the java generation etc.

**Comment by rmtmckenzie** [comment]
The project I'm writing has a dependency on flutter_sodium which has a dependency on libsodium-jni-aar:2.0.2-SNAPSHOT... so if it's possible to push an update to that if the PR checks out I'd really appreciate it =).

**Comment by joshjdevl** [comment]
Merged pull request #120
