### ISSUE TITLE
ndk-build

### ISSUE THREAD

**Issue by AlexanderKovalchuk** [joshjdevl/libsodium-jni#122]
Hi,
i'm trying to bould your project for Android and getting this errors:
42 warnings generated.
[armeabi-v7a] SharedLibrary  : libsodiumjni.so
/jni/sodium_wrap.c:6021: error: undefined reference to 'crypto_pwhash_scryptsalsa208sha256_saltbytes'
/jni/sodium_wrap.c:6033: error: undefined reference to 'crypto_pwhash_scryptsalsa208sha256_strbytes'
/jni/sodium_wrap.c:6045: error: undefined reference to 'crypto_pwhash_scryptsalsa208sha256_strprefix'
jni/sodium_wrap.c:6057: error: undefined reference to 'crypto_pwhash_scryptsalsa208sha256_opslimit_interactive'
jni/sodium_wrap.c:6069: error: undefined reference to 'crypto_pwhash_scryptsalsa208sha256_memlimit_interactive'
jni/sodium_wrap.c:6081: error: undefined reference to 'crypto_pwhash_scryptsalsa208sha256_opslimit_sensitive'
jni/sodium_wrap.c:6093: error: undefined reference to 'crypto_pwhash_scryptsalsa208sha256_memlimit_sensitive'
jni/sodium_wrap.c:6125: error: undefined reference to 'crypto_pwhash_scryptsalsa208sha256'
jni/sodium_wrap.c:6163: error: undefined reference to 'crypto_pwhash_scryptsalsa208sha256_str'
jni/sodium_wrap.c:6193: error: undefined reference to 'crypto_pwhash_scryptsalsa208sha256_str_verify'
jni/sodium_wrap.c:6237: error: undefined reference to 'crypto_pwhash_scryptsalsa208sha256_ll'

clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [../kalium-jni/obj/local/armeabi-v7a/libsodiumjni.so] Error 1

Have you any idea, what am i doing wrong? TY

**Comment by joshjdevl** [comment]
There is a Docker container here that you can use.
https://hub.docker.com/r/joshjdevl/libsodium-jni/

Otherwise please follow the linux build here or mac build here
https://github.com/joshjdevl/libsodium-jni/blob/master/.travis.yml#L22
https://github.com/joshjdevl/libsodium-jni/blob/master/.travis.yml#L31
