### ISSUE TITLE
crypto_kdf API support

### ISSUE THREAD

**Issue by schwamic** [joshjdevl/libsodium-jni#130]
Hey, thanks for this great library! I have seen that 2 months ago crypto_kdf was added to the master. Are there plans for a new release? I am looking forward to use [key_derivation >= 1.0.12](https://download.libsodium.org/doc/key_derivation#key-derivation-with-libsodium-greater-than-1-0-12).

**Comment by joshjdevl** [comment]
Thanks. [v2.0.2](https://github.com/joshjdevl/libsodium-jni/releases/tag/v2.0.2) has been [released](https://oss.sonatype.org/#nexus-search;quick~libsodium). Please let me know.

**Comment by schwamic** [comment]
Perfetto. Grazie mille!
