### ISSUE TITLE
More a question than an issue...

### ISSUE THREAD

**Issue by srgoldman** [joshjdevl/libsodium-jni#15]
I want to use my Java library which uses kalium on linux, mac, and android. What's the best way to do this given the different implementations? I'm using IntelliJ if that would help customize the builds. Obviously I want to avoid duplicating code for the different platforms and would like to distribute as few components as possible.

Thanks,
Seth

**Comment by joshjdevl** [comment]
Hello Seth,

I've updated the Readme with points to the JAR and AAR artificacts. Please give those a try.

Thanks
