### ISSUE TITLE
Not correct work with secretbox

### ISSUE THREAD

**Issue by emstlk** [joshjdevl/libsodium-jni#16]
I want reuse a buffer for secretbox methods like `crypto_secretbox_xsalsa20poly1305` and `crypto_secretbox_xsalsa20poly1305_open`

But tests failed if I use the same buffer to in and out arrays, for example

```
// buffer size is 32 + data.length
Sodium.crypto_secretbox_xsalsa20poly1305(buffer, buffer, buffer.length, nonce, key)
```

The out array becames with 32 zero bytes at the begining, without MAC

From [libsodium docs](http://doc.libsodium.org/secret-key_cryptography/authenticated_encryption.html):

> `c` and `m` can overlap, making in-place encryption possible. However do not forget that 
> `crypto_secretbox_MACBYTES` extra bytes are required to prepend the tag.

**Comment by joshjdevl** [comment]
Could you please submit a test case to reproduce the issue?
