### ISSUE TITLE
Error when running `mvn clean install`

### ISSUE THREAD

**Issue by hbmartin** [joshjdevl/libsodium-jni#19]
Hi, I am getting this error when I try to run the last build step:
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/haroldmartin/Documents/kalium-jni/src/test/java/org/abstractj/kalium/keys/VerifyKeyTest.java:[25,43] error: cannot find symbol
[ERROR]  package org.abstractj.kalium.encoders
/Users/haroldmartin/Documents/kalium-jni/src/test/java/org/abstractj/kalium/keys/VerifyKeyTest.java:[25,0] error: static import only from classes and interfaces
[ERROR] /Users/haroldmartin/Documents/kalium-jni/src/test/java/org/abstractj/kalium/keys/KeyPairTest.java:[23,43] error: cannot find symbol
[ERROR]  package org.abstractj.kalium.encoders
...
and so on with many more like errors

**Comment by joshjdevl** [comment]
Hello,

I noticed that you submitted a pull request for the [build-mac](https://github.com/joshjdevl/kalium-jni/blob/master/build-mac.sh) script. Was this able to resolve the error?

Thanks

**Comment by joshjdevl** [comment]
Hello,

There is a [Mac](build-mac.sh) and [Linux](build-linux.sh) build script available now. Closing issue for now.

Thanks,
Josh
