### ISSUE TITLE
compile.sh fails

### ISSUE THREAD

**Issue by alexkeramidas** [joshjdevl/libsodium-jni#21]
I don't think it is an issue but I do not know where else to put it

I am trying to compile the latest version of libsodium-jni in order to use it for an Android project.
While previous version compiled and failed at the maven step, this latest one fails at sodium_wrap.c.

Specifically 
sodium_wrap.c:781:20: fatal error: sodium.h: No such file or directory (which is true as I think it expects it to be the JNI folder)

As it happens the docker files are somewhat outdated, do not include all the functions and the single .so file from there refers only to the arm processors.

I am running this on an Ubuntu VM. Maybe it is my fault and I am not downloading the correct packages to the correct folders.

Should the libsodium folder be inside the libsodim-jni folder?
Should it be outside? And actually where in the system should I do all the git cloning for the whole thing to compile and then produce the .jar snapshop?

I currently do the git cloning in the /home/user path. 

NDK and JAVA are declared properly.

Thanks in advance!

**Comment by joshjdevl** [comment]
Sorry, I'm still working on cleaning up the instructions and creating a release.

Please try the Dockerfile [here](https://github.com/joshjdevl/libsodium-jni/blob/master/Dockerfile). I just pushed a commit that address the gradle build command. Once you clone [libsodium-jni](https://github.com/joshjdevl/libsodium-jni), please run "docker-compose build"

Thanks

**Comment by alexkeramidas** [comment]
OK great thank you!
You can leave the issue open until everything is resolved as I will be
compiling the library several times the next few weeks.

Moreover, what seems to work is skipping the compile.sh step doing the
ndk-build and then using the .so files in the jniLibs project folder and
your uncompiled java project code .ie no .jar file.

Keep up the good work.

**Comment by joshjdevl** [comment]
Hello,

I've also added both JAR and AAR artifacts and updated the Readme. Please let me know of any further issues. I'm closing this issue for now.

Thanks
