### ISSUE TITLE
JDK 7 Build

### ISSUE THREAD

**Issue by vlivanov** [joshjdevl/libsodium-jni#22]
As I see there are no troubles to compile the library with minSdkVersion 14 and jdk 7. As Android doesn't support java 8, and it is necessary to use retrolambda(which is not perfect) to workaround java 8 issues, it would be extremely useful to provide java 7 binaries.

**Comment by joshjdevl** [comment]
Thank you, yes agreed. I've pushed new artificats as <version>1.0.2-SNAPSHOT</version> and updated the readme.
