### ISSUE TITLE
fatal: reference is not a tree when running build.sh

### ISSUE THREAD

**Issue by antichaosdb** [joshjdevl/libsodium-jni#26]
After git submodule update I get
fatal: reference is not a tree: c3d391b0baa9ce8615634f842e2cfa441e5acd8a
Unable to checkout 'c3d391b0baa9ce8615634f842e2cfa441e5acd8a' in submodule path 'libsodium'

Is there a reason it needs to use a specific old commit?  Can I use the latest libsodium by doing 
git submodule update --remote --merge 
instead?

**Comment by joshjdevl** [comment]
Using the latest stable is fine, there is no reason to use a specific old commit.

We need to update the scripts.

**Comment by joshjdevl** [comment]
Scripts have been updated.
