### ISSUE TITLE
Not on maven central?

### ISSUE THREAD

**Issue by danhawkes** [joshjdevl/libsodium-jni#29]
Am confused:
The readme lists maven coordinates, and the gradle scripts look set up to deploy to central. I even found a sonatype [issue](https://issues.sonatype.org/browse/OSSRH-20448) about creating the group ID.

...but I can't find it: <https://search.maven.org/#search%7Cga%7C1%7Ccom.github.joshjdevl.libsodiumjni>

Has it been removed?

**Comment by snowdream** [comment]
@danhawkes  https://oss.sonatype.org/#nexus-search;quick~com.github.joshjdevl.libsodiumjni

it can be found.

**Comment by danhawkes** [comment]
Ah, that makes sense. Sonatype OSS != maven central, so that's why the issue is for sonatype.
Might be worth mentioning which repository it's in in the readme.
https://oss.sonatype.org/content/repositories/snapshots/

**Comment by joshjdevl** [comment]
Thank you for catching this! I've updated the readme 177700e93a58216d23f6963fd3d7961e618bc7e4

**Comment by danhawkes** [comment]
Great, thanks for the help.
