### ISSUE TITLE
sodium_init()?

### ISSUE THREAD

**Issue by Screeze** [joshjdevl/libsodium-jni#3]
Hi,
I was wondering how kalium is dealing with the need to call sodium_init() before usage of any function? In particular i think I'm missing the point where the number generator gets initialized? It doesn't seem possible to do that on my own, is this done automatically? Is there any possibility to inject a seed for the random number generator?

Thanks for your help.

**Comment by ge0rg** [comment]
kalium-jni neither calls nor exposes sodium_init(), as opposed to [kalium](https://github.com/abstractj/kalium).

The random number generator will be initialized on first use in libsodium (better not try to call it from  multiple threads), however some other aspects like CPU-specific optimizations will never be initialized properly.

**Comment by joshjdevl** [comment]
sodium_init() is available, please see [here](https://github.com/joshjdevl/libsodium-jni/blob/master/src/main/java/org/libsodium/jni/Sodium.java#L12)

There is no automatic invocation as the api is available for each application to call upon initialization depending on your application's needs and lifecycle.

Closing issue.
