### ISSUE TITLE
Prebuilt AAR with android64-v8a.so ?

### ISSUE THREAD

**Issue by matt-thinair** [joshjdevl/libsodium-jni#33]
Hey guys, is there a prebuilt aar with the android64-v8a.so included? I see that support has been added but would like pull the aar from maven rather than build it by hand.

**Comment by joshjdevl** [comment]
Thanks for the reminder. I have not built it yet, though I will be by end of this week.

**Comment by joshjdevl** [comment]
v1.0.3 jar and aar has been pushed to the sonatype snapshot repo.
