### ISSUE TITLE
howto build libkaliumjni.so ?

### ISSUE THREAD

**Issue by zoff99** [joshjdevl/libsodium-jni#35]
this repo does no longer exist:
https://github.com/joshjdevl/kalium-jni

how do i build libkaliumjni.so ?

**Comment by joshjdevl** [comment]
This repository has been renamed to https://github.com/joshjdevl/libsodium-jni

The default library name is libsodiumjni.so

The mac library will be called libsodiumjni.jnilib

The shared libraries are included in the aar archive which is available in the sonatype repository mentioned in the readme.

If you need to build it, please refer to the readme for OS specific scripts. There is also a docker container available.
