### ISSUE TITLE
Publish on Maven Central

### ISSUE THREAD

**Issue by bannmann** [joshjdevl/libsodium-jni#36]
Now that you have a release build (1.0.3), you should really publish this to Maven Central.

On a related note, the readme currently says "libsodium-jni is a work in progress". The readme should be clear on what stuff, if any, is missing and whether the library can be used for production purposes.

**Comment by joshjdevl** [comment]
Thanks, I am currently working on this now.

Documentation has been updated. This is being used in production.

**Comment by strooooke** [comment]
Is there any way I could help with publishing to Maven Central? Depending on a snapshot version is just that great.

**Comment by joshjdevl** [comment]
Thank you. The sonatype doc was easier to understand so I did that first. I'll be going through the maven central documentation in the next few days. If there is any scripts, pom updates, or gradle updates that you might know that would help out. I can then take care of the registration and signing aspects.

**Comment by joshjdevl** [comment]
1.0.5 has been [released](https://oss.sonatype.org/#nexus-search;quick~libsodium).

Can you please confirm that you can download?

**Comment by joshjdevl** [comment]
Also, I'm not sure how to close the repository when using gradle from the command line. I tried running the closeRepository command, though I receive the following. Any ideas?

> 
> A problem was found with the configuration of task ':closeRepository'.
> > No value has been specified for property 'packageGroup'.

**Comment by strooooke** [comment]
I can download, build, my tests run fine with
```
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/comgithubjoshjdevl-1000/" }
...
}
...
dependencies {
  compile "com.github.joshjdevl.libsodiumjni:libsodium-jni-aar:1.0.5@aar"
...
}
```

The aar is not available via mavenCentral. I guess this might be related to the unfinished repository modification process you mentioned above; I'll look into that now.

**Comment by strooooke** [comment]
A build.gradle that uses the nexus staging plugin: https://github.com/Codearte/gradle-nexus-staging-plugin does not seem to exist in this repo, so I can't look there. The linked doc shows how it should look and that it should define the property `packageGroup`. I found this: https://github.com/Codearte/gradle-nexus-staging-plugin/issues/23#issuecomment-226601004  concerning the correct value for `packageGroup`.

**Comment by joshjdevl** [comment]
I'm able now to run the following commands. Though not sure what else is needed to get the AAR into releases?

```
gradle uploadArchives
gradle closeAndPromoteRepository
```

**Comment by joshjdevl** [comment]
Also, how can I drop older Staging Repositories?

**Comment by joshjdevl** [comment]
I pushed 1.0.6 of the AAR. Still trying to figure out how to drop the Staging Repository from the command line when finished.

**Comment by strooooke** [comment]
https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.github.joshjdevl.libsodiumjni%22  looks good to me. Downloads, runs, tests great.

There's no need to drop the staging repo - after closing it, you _either_ drop it (if it were a bad release) _or_ release it (which you did). I assume that cleanup of the temporary repo will be automatic - ah, seems to have already happened.

Looks like the nexus staging _maven_ (not gradle) plugin can also drop, or do anything remotely. But that looks pretty annoying to integrate with the gradle build.

**Comment by joshjdevl** [comment]
Thanks!

**Comment by strooooke** [comment]
Thanks to _you_!
