### ISSUE TITLE
What's up with BLAKE2B?

### ISSUE THREAD

**Issue by strooooke** [joshjdevl/libsodium-jni#37]
There's code wrapping blake2b in src/main/java/org/libsodium/jni/crypto/Hash.java but it's commented out. Why is that? Is it unsafe, broken or wrong?

**Comment by joshjdevl** [comment]
The sodium blake2b interfaces are always [available](https://github.com/joshjdevl/libsodium-jni/blob/master/src/main/java/org/libsodium/jni/Sodium.java#L652) via Sodium.java. The tests were commented out as they weren't updated.

The wrappers and tests are [uncommented](https://github.com/joshjdevl/libsodium-jni/blob/master/src/test/java/org/libsodium/jni/crypto/HashTest.java#L122) now.

It should be ok to use.

**Comment by strooooke** [comment]
Cool, thanks a lot!
