### ISSUE TITLE
crypto_aead_chacha20poly1305_ietf_encrypt() parameters

### ISSUE THREAD

**Issue by monicaphalswal** [joshjdevl/libsodium-jni#38]
I want to use `crypto_aead_chacha20poly1305_ietf_encrypt()` function in my project. It has a parameter` int[] clen_p`. From what I understand, it's the cipher length. So, why is it an integer array and not just an integer?

**Comment by joshjdevl** [comment]
This is how the library is [defined](https://download.libsodium.org/doc/secret-key_cryptography/ietf_chacha20-poly1305_construction.html), please check with libsodium.

**Comment by monicaphalswal** [comment]
Yes, in libsodium` clen `is `unsigned long long *` but here it's an integer array.
