### ISSUE TITLE
Make it latest stable NDK (r13b)  compatible

### ISSUE THREAD

**Issue by ppmag** [joshjdevl/libsodium-jni#39]
Stable branch of libsodium now is NDK r13b ready, moreover build scripts fail when 
used with r12b NDK due to new '--force' arg used for ndk-build.

I was trying to change manually NDK version in setenv.sh to r13b,
but some of 64bit arch fail during build process.

It would be great to have "libsodium-jni"  r13b ready.

**Comment by joshjdevl** [comment]
Thanks for posting this.

Any possibility of creating a branch of the changes that you already attempted, as well as any logs or errors messages? That would make it easier and save time.

**Comment by joshjdevl** [comment]
Created a branch "ndk-r13b" to update the NDK.

The "--force" argument is only required if an existing install directory already exists. For the automated builds it is not required. If you are running locally and the directory exists, please either use the argument manually or remove the directory.

Consistently receiving the following [error](https://travis-ci.org/joshjdevl/libsodium-jni/builds/198240538), though do not know why it's only now appearing with the updated ndk?

"warning: shared library text segment is not shareable"

**Comment by joshjdevl** [comment]
@felixvf has submitted pull request #43  to solve this. This has been merged to master.
