### ISSUE TITLE
there are problems with Sodium.crypto_generichash_init()

### ISSUE THREAD

**Issue by yuhanXie** [joshjdevl/libsodium-jni#40]
when i run this method ,the app on android will crash, the message: jarray is an invalid stack indirect reference table or invalid reference: 0xffe43950 (0x6a09e667).
Sodium.crypto_hash_sha256_init() also has the same problem

**Comment by joshjdevl** [comment]
Are you able to provide a reproducable test case?

**Comment by yuhanXie** [comment]
public void testHash() {
        byte[] state = new byte[Sodium.crypto_generichash_statebytes()];
        byte[] hash = new byte[Sodium.crypto_generichash_bytes()];
        byte[] key = new byte[Sodium.crypto_generichash_keybytes()];
        Sodium.randombytes(key, key.length);
        if (0 == Sodium.crypto_generichash_init(state, key, key.length, hash.length)) {
            Log.e("tag", "init success");
        } else {
            Log.e("tag", "init failed");
        }
    }

this is the test case, i think there are some problems with the state, the error i found is at the function releaseByteArrayElements().

**Comment by yuhanXie** [comment]
**the stacktrace:**
JNI DETECTED ERROR IN APPLICATION: jarray is an invalid stack indirect reference table or invalid reference: 0x7fef51bdb8 (0xf2bde928)
02-06 09:51:56.551 3876-3876/android.alex.com.sodium A/art: art/runtime/java_vm_ext.cc:410]     in call to ReleaseByteArrayElements
02-06 09:51:56.551 3876-3876/android.alex.com.sodium A/art: art/runtime/java_vm_ext.cc:410]     from int org.libsodium.jni.SodiumJNI.crypto_generichash_init(byte[], byte[], int, int)

**Comment by joshjdevl** [comment]
This is fixed in master f3f1ec05134a0b083488f6428c9233af465bf5b0

**Comment by yuhanXie** [comment]
it is fixed, Thank you very much! how do you fix this? may you explain this?

**Comment by joshjdevl** [comment]
The SWIG typemap(in) needed to be updated.
