### ISSUE TITLE
Howto build / run on windows

### ISSUE THREAD

**Issue by zetisam** [joshjdevl/libsodium-jni#42]
I'm looking to use libsodium in my (non-android) java application.

This project seems promising, as it exposes more of the libsodium api than Kalium, but I'm unable to get it to work.

It's looking for sodiumjni.dll, which I assume is not the same as the sodium.dll files available here
https://download.libsodium.org/libsodium/releases/ ?

Do you have any idea where I can obtain this sodiumjni.dll file? It seems like this is the missing piece to get this to work.

thx!

**Comment by joshjdevl** [comment]
We currently build for mac and linux. You could try modifying the mac/linux scripts to compile the windows dll.
