### ISSUE TITLE
New version 1.0.12

### ISSUE THREAD

**Issue by S1owaway** [joshjdevl/libsodium-jni#56]
Hello! Can you asseble new version for latest release (1.0.12)?

**Comment by joshjdevl** [comment]
There is a [branch](https://github.com/joshjdevl/libsodium-jni/tree/libsodium-1.0.12). Though it does not build. You are welcome to help figure out what changed.

**Comment by spscream** [comment]
@joshjdevl changelog of libsodium contains following things in 1.0.12:
+ - AVX2 detection is more reliable.
+ - The pthreads library is not required any more when using MingW.
+ - `contrib/Findsodium.cmake` was added as an example to include
+libsodium in a project using cmake.
+ - Compatibility with gcc 2.x has been restored.
+ - Minimal builds can be checked using `sodium_library_minimal()`.
+ - The `--enable-opt` compilation switch has become compatible with more
+platforms.
+ - Android builds are now using clang on platforms where it is
+available.

this could be an issue with it

**Comment by spscream** [comment]
and also dist-build/android-build.sh was changed

**Comment by spscream** [comment]
And may be it is switched to latest stable ndk r14b, may be this causes building problems.

**Comment by joshjdevl** [comment]
I've created another [branch](https://github.com/joshjdevl/libsodium-jni/tree/feature-ndk-sdk-update) to upgrade the Android SDK, NDK, and Gradle. However, still receiving quite a few errors.

Searching I see other developers having issues and reporting to Google regarding the licensing prompts which breaks CI, the new sdkmanager, etc.

Any ideas?

**Comment by S1owaway** [comment]
We are trying to assemble but as yet to no avail

**Comment by joshjdevl** [comment]
I was able to make progress in the [branch](https://github.com/joshjdevl/libsodium-jni/tree/libsodium-1.0.12). Though running into issues with clang and mips32.

**Comment by S1owaway** [comment]
I see you were able to assemble the latest build. Can you update the Maven repo? Thank you!
https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.github.joshjdevl.libsodiumjni%22

**Comment by joshjdevl** [comment]
Still working on getting the android emulator working with the build and new android sdk.

Were you able to build locally and verify the libraries?

**Comment by henry74918** [comment]
Hello, I'm totally newbie for libsodium and libsodium-jni.
I try to checkout branch 1.0.12 and try to build libsodium but I failed.
The error mssage is "):crypto_pwhash/scryptsalsa208sha256/crypto_scrypt-common.c:function escrypt_r: error: undefined reference to '__strrchr_chk'"

How can I fix it and continue to build?
I need libsodium 1.0.12 because I need the new crypto.kx._*() apis. https://download.libsodium.org/doc/key_exchange/
Any help is appreciate, Thanks!

**Comment by joshjdevl** [comment]
@henry74918 please try the latest in master or the docker container.

**Comment by henry74918** [comment]
It works! all platform can build with no problem.
Thanks for help!
Btw, do you have a plan to push a new aar for libsodium 1.0.12 or newer version?

**Comment by joshjdevl** [comment]
@henry74918 It's available in the nightly snapshots.
