### ISSUE TITLE
Xchacha20Poly1305  algorithm

### ISSUE THREAD

**Issue by yuhanXie** [joshjdevl/libsodium-jni#67]
Hi: 
    jedisct1  updated an algorithm called Xchacha20Poly1305, Can you provide a new sodium.i file or tell me how to generate sodium.i ?
     thank you!

**Comment by joshjdevl** [comment]
Thank you for letting us know. Could you please create a pull request adding the definition to [sodium.i](https://github.com/joshjdevl/libsodium-jni/blob/master/jni/sodium.i) and the Java definitions to [SodiumJNI.java](https://github.com/joshjdevl/libsodium-jni/blob/master/src/main/java/org/libsodium/jni/SodiumJNI.java) and [Sodium.java](https://github.com/joshjdevl/libsodium-jni/blob/master/src/main/java/org/libsodium/jni/Sodium.java)?

**Comment by yuhanXie** [comment]
what's the meaning of " add the definition to sodium.i ",  i don't know how to generate a new sodium.i using the C source code.

**Comment by joshjdevl** [comment]
The build process of SWIG will take care of generating the relevant code. Only thing needed is the function definition header to be added to sodium.i

**Comment by yuhanXie** [comment]
ok, I know , thank you !

**Comment by kalaspuffar** [comment]
@joshjdevl @yuhanXie Can we close this issue?
