### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for int org.libsodium.jni.SodiumJNI.crypto_box_seal_open

### ISSUE THREAD

**Issue by shainsingh89** [joshjdevl/libsodium-jni#68]
I am trying to access box sealed method 
`org.libsodium.jni.SodiumJNI.crypto_box_seal_open(chipherText,output,chipherText.length,publicKey,privateKey);`
but it giving me below error

`java.lang.UnsatisfiedLinkError: No implementation found for int org.libsodium.jni.SodiumJNI.crypto_box_seal_open(byte[], byte[], int, byte[], byte[]) (tried Java_org_libsodium_jni_SodiumJNI_crypto_1box_1seal_1open and Java_org_libsodium_jni_SodiumJNI_crypto_1box_1seal_1open___3B_3BI_3B_3B)
                                                                              at org.libsodium.jni.SodiumJNI.crypto_box_seal_open(Native Method)  `

**Comment by kalaspuffar** [comment]
Hi @shainsingh89 

You're required to run NaCl.sodium(); before any calls to SodiumJNI. This will look in your library path for the native implementation. If you run the code on Android you just need to add the aar (Android Archive Library) to your gradle file. 
On the other hand, if you're trying to run the code locally you need to build the library using any of the build scripts and add the native library file to your library path. (.so file)

Best regards
Daniel
