### ISSUE TITLE
No other charset than US-ASCII

### ISSUE THREAD

**Issue by yleyvag** [joshjdevl/libsodium-jni#75]
I'm trying to encrypt/decrypt strings that contains latin characters like á,é,í,ó,ú but when I decrypt I receive ? insted the latin character. I'm sure that's because the static CHARSET defined in Encoder.java.

**Comment by joshjdevl** [comment]
Created commit for [utf8](https://github.com/joshjdevl/libsodium-jni/commit/1334b5a5ab3cce514e9aa84de84b270b11921a50).
