### ISSUE TITLE
Question on 1.0.7 aar release

### ISSUE THREAD

**Issue by bufke** [joshjdevl/libsodium-jni#80]
Sorry if this is a dumb question - I feel REALLY REALLY dumb when I do anything with java dependencies and repos. I'm trying to upgrade from 1.0.7 snapshot to 1.0.7 release.

But the releases version doesn't appear to exist. Check out

https://oss.sonatype.org/content/repositories/releases/com/github/joshjdevl/libsodiumjni/libsodium-jni-aar/

Previously I had this in my include.gradle. I'm kind of just guessing that it's at releases for a release as 1.0.6 is there.

```
repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}

dependencies {
	compile 'com.github.joshjdevl.libsodiumjni:libsodium-jni-aar:1.0.7-SNAPSHOT'
}
```

**Comment by joshjdevl** [comment]
Fixed.
