### ISSUE TITLE
Output doesn't match expected hash

### ISSUE THREAD

**Issue by smasher816** [joshjdevl/libsodium-jni#81]
Hi, I'm sure I am probably missing something stupid but I can't get the output to match the official argon2 cli.

I am using `com.github.joshjdevl.libsodiumjni:libsodium-jni-aar:1.0.7`

Here is my Java code (inside MainActivity.java for an android app).
```
Sodium sodium = NaCl.sodium(); //To init
byte[] key = new byte[32];
byte[] passwd = "hunter2".getBytes(StandardCharsets.US_ASCII);
byte[] salt = "somesalt".getBytes(StandardCharsets.US_ASCII);
int t = 3;
int m = 32768; //2^15
Sodium.crypto_pwhash(
    key, key.length,
    passwd, passwd.length,
    salt,
    t, m*1024,
    Sodium.crypto_pwhash_alg_argon2i13());
Log.d("ArgonPass", Encoder.HEX.encode(key));
```

Which produces `6c4d481e349a7c9f26265c1ad49eff79c0247390e89744ce9b62867ff54f7e71`.

For reference here is the expected hash

```
$ echo -n "hunter2" | argon2 "somesalt" -t 3 -m 15 -l 32 -i -v 13
Type:		Argon2i
Iterations:	3 
Memory:		32768 KiB
Parallelism:	1 
Hash:		5025aadc4b722b3ce2de6935eb2f6c5d5ab98f7bd4bbdb73d0f1b190552d7815
Encoded:	$argon2i$v=19$m=32768,t=3,p=1$c29tZXNhbHQ$UCWq3EtyKzzi3mk16y9sXVq5j3vUu9tz0PGxkFUteBU
```

I have tried using `crypto_pwhash_str(key, passwd, passwd.length t, m*1024)`. And I get an output with `$argon2i$v=19$m=32768,t=3,p=1` so it appears I am passing in the work parameters correctly. I used the *1024 because the libsodium docs say the memory is specified in bytes while the argon2cli uses KiB. I have also tried using different encoding formats and raw character arrays to no avail.

**Comment by kalaspuffar** [comment]
Hi @smasher816 

Seems like the two functions are initialized differently. So the program uses another set of bytes that only zeros in the salt when you don't supply the full 16 bytes of salt.

In case of the library function it seems to set these bytes to zero and then you see differing results.

I tried to supply "somesaltsomesalt" to both functions and got the same hash.

Hope this helps.

Best regards
Daniel
