### ISSUE TITLE
Outdated SWIG-generated files

### ISSUE THREAD

**Issue by manueljacob** [joshjdevl/libsodium-jni#89]
After a build, the files "src/main/java/org/libsodium/jni/Sodium.java" and "src/main/java/org/libsodium/jni/SodiumJNI.java" are changed and git "complains" about this (at least on my machine - I'm using libsodium-jni as a subrepository).

Why are the SWIG-generated files in the repository in the first place? It seems like they are re-generated on every build. Personally I avoid putting auto-generated files in the repository. I'm not sure whether this is just my personal preference or generally accepted best practice. In the end it's your decision.

If you decide to leave them in the repository, please commit the current version of them, as some functions were removed.

**Comment by joshjdevl** [comment]
Updated.
