### ISSUE TITLE
java.lang.UnsatisfiedLinkError using project in tests

### ISSUE THREAD

**Issue by robsmall** [joshjdevl/libsodium-jni#95]
I have the following issue when trying to test the code via unit tests.

```
java.lang.UnsatisfiedLinkError: no sodiumjni in java.library.path

	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.libsodium.jni.NaCl.<clinit>(NaCl.java:29)
```

I include the library in my Android project like so:

build.gradle:
```
dependencies {
  ...

  compile 'com.github.joshjdevl.libsodiumjni:libsodium-jni-aar:1.0.7'

  ...

  testCompile 'com.google.guava:guava:18.0'
  testCompile 'junit:junit:4.10'
}
```

I have also tried using the non aar version, but to no avail.

Anyone know how to solve this? Do I need to just build the project manually? Building/running tests using Android Studio on a Mac.

**Comment by joshjdevl** [comment]
Both the aar and jar need to be included dependency, is only the aar added?

**Comment by robsmall** [comment]
Thanks for the quick response! I tried using both but still had the same issue so I omitted the jar.

**Comment by robsmall** [comment]
Looks like it may be an android issue, not an issue with this library

https://stackoverflow.com/questions/34802667/unit-test-java-class-that-loads-native-library/

**Comment by kalaspuffar** [comment]
Hi @robsmall.

Well you're both right and...

The thread on StackOverflow talks about not being able to test the library without using instrumentation testing. And this is a limitation and separation that it quite reasonable. In case of the aar build these native libraries are only available in an Android format so if you use the instrumentation tests you will actually run the test on the phone/emulator.

On the other hand, if you build the native libraries and install them on your system you should be able to run the test locally using JUnit as well.

Best regards
Daniel
